<a href="https://colab.research.google.com/github/luiz-star/Numpy_Criacao_Arrays/blob/main/Numpy_criacao_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [ ]:
# importando as Bibliotecas
import numpy as np

# Criação de Arrays

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [ ]:
#criação de um array 1 D: [1, 2, 3]
l = [1, 2, 3]
x = np.array(l)
print('x:', x) 
print('shape:', x.shape)

x: [1 2 3]
shape: (3,)


In [ ]:
#criação de um array 2 D: listas aninhadas
l = [[1, 2],[3, 4]]
x = np.array(l)
print('x:\n', x)
print('shape:', x.shape)


x:
 [[1 2]
 [3 4]]
shape: (2, 2)


In [ ]:
#array contendo apenas 0's
dim = (2, 2)  # linhas e colunas
x = np.zeros(dim)
print('x:\n', x)
print('shape:', x.shape)

x:
 [[0. 0.]
 [0. 0.]]
shape: (2, 2)


In [ ]:
#array contendo apenas 1's
size = (2, 2)  #linhas e colunas
x = np.ones(size)
print('x:\n', x)
print('shape:', x.shape)

x:
 [[1. 1.]
 [1. 1.]]
shape: (2, 2)


In [ ]:
type(x)

numpy.ndarray

In [ ]:
#criação de valores dentro de um intervalo

# valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(start=x_min, stop=x_max, num=6)
print('x:', x)
print('shape:', x.shape)

x: [ 5.  7.  9. 11. 13. 15.]
shape: (6,)


In [ ]:
np.linspace?

In [ ]:
#criação de matriz identidade
n = 4
x = np.eye(n)
print('x:\n', x)
print('shape:', x.shape)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape: (4, 4)


In [ ]:
# criação de valores aleatórios
# np.random.seed(10)
x = np.random.random(size=(2, 3))
print('x:\n', x)
print('shape:', x.shape)

x:
 [[0.24141295 0.5350477  0.05063852]
 [0.11342032 0.12805938 0.02735293]]
shape: (2, 3)


# Indexação de arrays

In [ ]:
# Os indices no Python vão de 0 a n-1
# onde n é o tamanho da dimensão
x = np.linspace(start=10, stop=100, num=10)
print('x:', x)
print('shape:', x.shape)

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape: (10,)


In [ ]:
# Extração de elementos
print('x:', x)
print('primeiro elemento:', x[0])
print('segundo elemento:', x[1])
print('ultimo elemento:', x[9])
print('ultimo elemento:', x[-1]) # acessar de trás para frente

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
primeiro elemento: 10.0
segundo elemento: 20.0
ultimo elemento: 100.0
ultimo elemento: 100.0


In [ ]:
x[-5]  # acessando um elemento especifico 

60.0

In [ ]:
# slicing extração de subarrays:
print('x:', x)
print('dois primeiros elementos:', x[0:2]) # 2 é exclusivo
print( 'dois primeiros elementos:', x[:2])
print('dois ultimos elementos:', x[-2:]) 

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
dois primeiros elementos: [10. 20.]
dois primeiros elementos: [10. 20.]
dois ultimos elementos: [ 90. 100.]


In [ ]:
x[8:]

array([ 90., 100.])

In [ ]:
#slicing em arrays 2D (matrizes) 
x = x.reshape(2, 5)   # Reshape de x para 2 linhas e 5 colunas
print('x:', x)

x: [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [ ]:
# extração de elementos
print('primeira linha, segunda coluna:', x[0, 1])
print('segunda linha, penultima coluna:', x[1, -2])
print('ultima linha, ultima coluna:', x[1, 4])
print('ultima linha, ultima coluna:', x[-1, -1])




primeira linha, segunda coluna: 20.0
segunda linha, penultima coluna: 90.0
ultima linha, ultima coluna: 100.0
ultima linha, ultima coluna: 100.0


In [ ]:
print(x[1, 0])

60.0


In [ ]:
# slicing extração de subarrays
print('x:', x)
print('primeira linha inteira:', x[0, :])
print('primeira linha, segunda a quarta coluna:', x[0, 1:4])
print('ultima coluna inteira:\n', x[:, [-1]])

x: [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]
primeira linha inteira: [10. 20. 30. 40. 50.]
primeira linha, segunda a quarta coluna: [20. 30. 40.]
ultima coluna inteira:
 [[ 50.]
 [100.]]


In [ ]:
# Atenção com compartilhamento de memória em subarrays!!!
x = np.array([1, 2, 3])
print('x antes:', x)

y = x[:2]
y[0] = -100   # alteração do valor em y altera o valor em x
print('x depois:', x)

x antes: [1 2 3]
x depois: [-100    2    3]


In [ ]:
# Atenção com compartilhamento de memória em subarrays!!!
x = np.array([1, 2, 3])
print('x antes:', x)

y = x[:2].copy()
y[0] = -100    # alteração do valor em y altera o valor de x
print('x depois:', x)

x antes: [1 2 3]
x depois: [1 2 3]
